# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Dev\Test Arch board'
    subscriptionId: 'fedf4c96-f367-4754-9324-961fc2ef4113'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'KirillTestRG'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'vm.json'
    deploymentMode: 'Incremental'